# Generated by Django 5.0 on 2024-01-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_contacts_socialnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=80, verbose_name='Чат ID')),
            ],
            options={
                'verbose_name': 'Чат ID',
                'verbose_name_plural': 'Чат ID',
            },
        ),
    ]
