# Generated by Django 5.0 on 2024-01-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('в_обработке', 'В обработке'), ('ожидание', 'Ожидание'), ('отправлено', 'Отправлено'), ('доставлено', 'Доставлено'), ('оплачено', 'Оплачено'), ('не_оплачено', 'Не оплачено')], default='ожидание', max_length=45, verbose_name='Статус'),
        ),
    ]
