# Generated by Django 5.0 on 2024-01-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='neme',
            new_name='name',
        ),
    ]
