# Generated by Django 5.0 on 2024-01-05 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True, verbose_name='Дата создания')),
                ('make', models.CharField(max_length=150, verbose_name='Марка машины')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_field', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Процент к курсу валюты',
            },
        ),
        migrations.CreateModel(
            name='CarName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=250, verbose_name='Наименование машины')),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.carmake', verbose_name='Марка машины')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos', models.JSONField(blank=True, default=list, null=True, verbose_name='Ссылки на фотографии')),
                ('name_product', models.CharField(blank=True, max_length=225, null=True, verbose_name='Название производителя')),
                ('model_year', models.IntegerField(blank=True, null=True, verbose_name='Год модели')),
                ('detail_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='номер детали')),
                ('v_i_n', models.CharField(blank=True, max_length=225, null=True, verbose_name='Идентификационный номер транспортного средства')),
                ('code_product', models.CharField(blank=True, max_length=225, null=True, verbose_name='Код продукта')),
                ('product_information', models.TextField(blank=True, null=True, verbose_name='Информация о продукте')),
                ('external_color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Внешний цвет')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стара цена')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Новая цена')),
                ('car_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.carname', verbose_name='Название производителя/название автомобиля')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
