# Generated by Django 5.0 on 2024-01-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmake',
            options={'verbose_name': 'Марка машины', 'verbose_name_plural': 'Марка машины'},
        ),
        migrations.AlterModelOptions(
            name='carname',
            options={'verbose_name': 'Наименование машины', 'verbose_name_plural': 'Наименование машины'},
        ),
        migrations.AlterModelOptions(
            name='exchangerates',
            options={'verbose_name': 'Процент к курсу валюты', 'verbose_name_plural': 'Процент к курсу валюты'},
        ),
    ]
