# Generated by Django 5.0 on 2024-01-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_carmake_options_alter_carname_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmake',
            name='create_date',
            field=models.DateTimeField(auto_created=True, verbose_name='Это создание'),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='make',
            field=models.CharField(max_length=125, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Новая цена'),
        ),
    ]
