# Generated by Django 5.0 on 2024-01-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_product',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Название Детали'),
        ),
    ]
