# Generated by Django 5.0 on 2024-01-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmake',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Это создание'),
        ),
    ]
