# Generated by Django 5.0 on 2024-01-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_in_won',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена на вон'),
        ),
    ]
